// Each opening entry has this shape:
//   key:         unique identifier used as the React list key
//   name:        display name shown on the card and in the game header
//   description: one-line summary shown on the card
//   playerColor: "w" or "b" — which side the user controls in the tutorial
//   moves:       ordered array of { side, from, to, explanation }
//     side:        "w" or "b" — which player makes this move
//     from / to:   algebraic square names (e.g. "e2", "e4")
//     explanation: text shown in the panel after the move is played
//
// The board flips automatically to show from playerColor's perspective.
// Opponent moves play themselves automatically; the user only makes moves
// where side === playerColor.

const OPENINGS = [
  // ── Defenses against 1.e4 (player as Black) ──────────────────────────────

  {
    key: "sicilian_defense",
    name: "Sicilian Defense",
    description: "Black's sharpest reply to 1.e4 — fight for the center without mirroring White.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4, claiming the center and opening lines for the bishop and queen." },
      { side: "b", from: "c7", to: "c5", explanation: "The Sicilian Defense. Black fights for d4 without giving White a symmetrical center. This is the most popular reply to e4 at all levels." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight toward the center, preparing d4." },
      { side: "b", from: "d7", to: "d6", explanation: "Supporting e5 and preparing to develop the dark-squared bishop to e6 or g4." },
      { side: "w", from: "d2", to: "d4", explanation: "White expands in the center. The tension is now high." },
      { side: "b", from: "c5", to: "d4", explanation: "Black trades the c-pawn for White's central d-pawn, gaining open lines and an asymmetrical position." },
      { side: "w", from: "f3", to: "d4", explanation: "White recaptures with the knight, keeping central control." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing the knight while attacking e4 — a powerful multi-purpose move." },
      { side: "w", from: "b1", to: "c3", explanation: "White defends e4 and develops another piece efficiently." },
      { side: "b", from: "a7", to: "a6", explanation: "The Najdorf Variation. Preventing Bb5+ and preparing b5 queenside expansion. Bobby Fischer's favorite weapon." },
    ],
  },
  {
    key: "french_defense",
    name: "French Defense",
    description: "A solid, strategic defense that leads to rich, complex middlegames.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "e7", to: "e6", explanation: "The French Defense. Black prepares d5, building a strong pawn chain while keeping the center closed for now." },
      { side: "w", from: "d2", to: "d4", explanation: "White occupies the center with both pawns." },
      { side: "b", from: "d7", to: "d5", explanation: "Challenging the center immediately. Now both sides have strong central pawns." },
      { side: "w", from: "b1", to: "c3", explanation: "White defends e4 with the knight — the Classical Variation begins." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing the knight and attacking e4, putting more pressure on White's center." },
      { side: "w", from: "c1", to: "g5", explanation: "White pins the f6 knight and prepares to increase pressure on d5 and e5." },
      { side: "b", from: "f8", to: "e7", explanation: "Breaking the pin calmly and preparing to castle kingside. A solid, classical response." },
      { side: "w", from: "e4", to: "e5", explanation: "White advances, gaining space and shifting the pawn structure." },
      { side: "b", from: "f6", to: "d7", explanation: "Retreating the knight while attacking the bishop on g5 — a key French Defense maneuver." },
    ],
  },
  {
    key: "caro_kann",
    name: "Caro-Kann Defense",
    description: "A solid reply to e4 — support the center with pawns and develop freely.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White claims the center with e4." },
      { side: "b", from: "c7", to: "c6", explanation: "The Caro-Kann. Black prepares d5 with solid pawn support, unlike the French where the light-squared bishop gets locked in." },
      { side: "w", from: "d2", to: "d4", explanation: "White reinforces the center." },
      { side: "b", from: "d7", to: "d5", explanation: "Striking at the center immediately. Black already has solid support from c6." },
      { side: "w", from: "b1", to: "c3", explanation: "White defends e4 with the knight." },
      { side: "b", from: "d5", to: "e4", explanation: "Black captures on e4, trading the d-pawn for White's e-pawn and inviting the knight to an exposed square." },
      { side: "w", from: "c3", to: "e4", explanation: "White recaptures with the knight, now centrally posted." },
      { side: "b", from: "c8", to: "f5", explanation: "The key move of the Classical Caro-Kann — developing the bishop outside the pawn chain before playing e6." },
      { side: "w", from: "e4", to: "g3", explanation: "White pushes the bishop, gaining space on the kingside." },
      { side: "b", from: "f5", to: "g6", explanation: "Retreating to a safe square. Black has a solid position with good piece activity." },
    ],
  },
  {
    key: "ruy_lopez",
    name: "Ruy Lopez",
    description: "The Spanish Opening — one of the oldest and most deeply studied openings in chess history.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "e7", to: "e5", explanation: "Black takes an equal share of the center." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight and attacks e5." },
      { side: "b", from: "b8", to: "c6", explanation: "Defending e5 with the knight — the natural and most common response." },
      { side: "w", from: "f1", to: "b5", explanation: "The Ruy Lopez. The bishop pins the knight that defends e5, creating indirect pressure on that pawn." },
      { side: "b", from: "a7", to: "a6", explanation: "The Morphy Defense — Black challenges the bishop immediately, forcing it to show its intentions." },
      { side: "w", from: "b5", to: "a4", explanation: "White retreats, maintaining the pin rather than trading bishop for knight." },
      { side: "b", from: "g8", to: "f6", explanation: "Counter-attacking e4 rather than chasing the bishop — a principled developing move." },
      { side: "w", from: "e1", to: "g1", explanation: "White castles, getting the king to safety and connecting the rooks." },
      { side: "b", from: "f8", to: "e7", explanation: "Preparing to castle. The Closed Ruy Lopez — one of the richest structures in chess." },
    ],
  },
  {
    key: "italian_game",
    name: "Italian Game",
    description: "A classical opening focused on rapid development and fighting for the center.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "e7", to: "e5", explanation: "Black stakes a claim in the center." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight and attacks e5." },
      { side: "b", from: "b8", to: "c6", explanation: "Defending e5 and developing the queenside knight." },
      { side: "w", from: "f1", to: "c4", explanation: "The Italian Game. White aims the bishop at f7, the weakest point in Black's starting position." },
      { side: "b", from: "f8", to: "c5", explanation: "The Giuoco Piano — Black mirrors White's setup, pointing the bishop at f2." },
      { side: "w", from: "c2", to: "c3", explanation: "Preparing d4 to expand in the center. White builds slowly." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing the knight and immediately pressuring e4." },
      { side: "w", from: "d2", to: "d4", explanation: "White expands in the center, now that c3 supports d4." },
      { side: "b", from: "e5", to: "d4", explanation: "Black trades to open the center, activate pieces, and relieve the central tension." },
    ],
  },
  {
    key: "scotch_game",
    name: "Scotch Game",
    description: "White opens the center early with d4, leading to sharp, tactical play.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "e7", to: "e5", explanation: "Black claims equal center space." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops and attacks e5." },
      { side: "b", from: "b8", to: "c6", explanation: "Defending e5 with the knight." },
      { side: "w", from: "d2", to: "d4", explanation: "The Scotch Game — White opens the center immediately rather than building up slowly." },
      { side: "b", from: "e5", to: "d4", explanation: "Black accepts the offered pawn, opening the position. The game becomes tactical." },
      { side: "w", from: "f3", to: "d4", explanation: "White recaptures, centralizing the knight powerfully." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing with tempo by attacking e4." },
      { side: "w", from: "b1", to: "c3", explanation: "White defends e4 and completes queenside development." },
      { side: "b", from: "f8", to: "c5", explanation: "The Classical Scotch — Black develops the bishop to an active diagonal, eyeing d4 and f2." },
    ],
  },
  {
    key: "petrov_defense",
    name: "Petrov Defense",
    description: "Black mirrors White's knight move, leading to a symmetrical and solid game.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "e7", to: "e5", explanation: "Black mirrors, staking equal center space." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight and attacks e5." },
      { side: "b", from: "g8", to: "f6", explanation: "The Petrov Defense — Black counter-attacks e4 instead of defending e5 directly." },
      { side: "w", from: "f3", to: "e5", explanation: "White accepts the pawn, capturing on e5." },
      { side: "b", from: "d7", to: "d6", explanation: "Attacking the knight and forcing it to move before Black recovers the pawn on e4." },
      { side: "w", from: "e5", to: "f3", explanation: "White retreats — taking Nxf6 instead allows Qxe4+, losing material." },
      { side: "b", from: "f6", to: "e4", explanation: "Black recaptures the pawn with the knight, restoring material equality." },
      { side: "w", from: "d2", to: "d4", explanation: "White stakes central space and opens lines." },
      { side: "b", from: "d6", to: "d5", explanation: "Solidifying the center. Black has a solid, equal position — the hallmark of the Petrov." },
    ],
  },
  {
    key: "kings_gambit",
    name: "King's Gambit",
    description: "White sacrifices a pawn for rapid development and a kingside attack. Learn to accept and hold on.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "e7", to: "e5", explanation: "Black mirrors, claiming an equal share of the center." },
      { side: "w", from: "f2", to: "f4", explanation: "The King's Gambit! White offers the f-pawn to open the f-file and gain central control." },
      { side: "b", from: "e5", to: "f4", explanation: "Accepting the gambit. Black takes the pawn and challenges White to prove the compensation is real." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight, preparing to castle and attack the f4 pawn." },
      { side: "b", from: "g7", to: "g5", explanation: "Holding the extra pawn. Risky but principled — Black stakes a claim to keep the material." },
      { side: "w", from: "f1", to: "c4", explanation: "White develops the bishop toward f7, the weakest point in Black's camp." },
      { side: "b", from: "f8", to: "g7", explanation: "Developing the bishop and reinforcing the g5 pawn. Black prepares to castle." },
      { side: "w", from: "d2", to: "d4", explanation: "White grabs more center space and opens lines for the attack." },
      { side: "b", from: "d7", to: "d6", explanation: "Solidifying Black's position and preventing e5 ideas while preparing queenside development." },
    ],
  },
  {
    key: "pirc_defense",
    name: "Pirc Defense",
    description: "A hypermodern defense — let White build a big center, then attack it from the flanks.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "d7", to: "d6", explanation: "The Pirc Defense begins. Black prepares Nf6 and g6, aiming for a hypermodern setup." },
      { side: "w", from: "d2", to: "d4", explanation: "White builds a large pawn center." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing the knight and putting pressure on e4." },
      { side: "w", from: "b1", to: "c3", explanation: "White supports the center and develops." },
      { side: "b", from: "g7", to: "g6", explanation: "Preparing to fianchetto the bishop — the cornerstone of the Pirc setup." },
      { side: "w", from: "f2", to: "f4", explanation: "The Austrian Attack — White goes for an aggressive, space-gaining plan." },
      { side: "b", from: "f8", to: "g7", explanation: "The bishop fianchetto is complete. Black's g7 bishop will pressure White's center for the whole game." },
      { side: "w", from: "g1", to: "f3", explanation: "White completes development and prepares to castle." },
      { side: "b", from: "e8", to: "g8", explanation: "Castling kingside — the king is safe and Black is ready to strike at White's center with c5 or e5." },
    ],
  },
  {
    key: "scandinavian_defense",
    name: "Scandinavian Defense",
    description: "Black immediately challenges White's e4 pawn — simple, active, and full of tricks.",
    playerColor: "b",
    moves: [
      { side: "w", from: "e2", to: "e4", explanation: "White opens with e4." },
      { side: "b", from: "d7", to: "d5", explanation: "The Scandinavian Defense — Black challenges the center at once rather than building up gradually." },
      { side: "w", from: "e4", to: "d5", explanation: "White accepts and captures the d5 pawn." },
      { side: "b", from: "d8", to: "d5", explanation: "Black recaptures with the queen, which looks risky but gives immediate activity." },
      { side: "w", from: "b1", to: "c3", explanation: "White develops and attacks the queen." },
      { side: "b", from: "d5", to: "a5", explanation: "The queen retreats to a5 — a well-known Scandinavian square where it eyes c7 and keeps pressure on the position." },
      { side: "w", from: "d2", to: "d4", explanation: "White occupies the full center." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing with tempo — the knight attacks e4 and prepares kingside castling." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the second knight." },
      { side: "b", from: "c8", to: "f5", explanation: "The bishop develops actively before the pawn chain closes. Black has a solid, active setup." },
    ],
  },

  // ── Defenses against 1.d4 (player as Black) ──────────────────────────────

  {
    key: "queens_gambit_declined",
    name: "Queen's Gambit Declined",
    description: "One of the most respected defenses against d4 — solid and positionally rich.",
    playerColor: "b",
    moves: [
      { side: "w", from: "d2", to: "d4", explanation: "White opens with d4, a solid move controlling the center." },
      { side: "b", from: "d7", to: "d5", explanation: "Black mirrors, establishing an equal central presence." },
      { side: "w", from: "c2", to: "c4", explanation: "The Queen's Gambit — White offers the c-pawn to undermine Black's central d5 pawn." },
      { side: "b", from: "e7", to: "e6", explanation: "The Queen's Gambit Declined. Black reinforces d5 with the pawn rather than accepting the gambit." },
      { side: "w", from: "b1", to: "c3", explanation: "White develops and keeps the pressure on d5." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing the most active piece first, pressuring e4 and preparing castling." },
      { side: "w", from: "c1", to: "g5", explanation: "White pins the f6 knight, aiming to double pressure on d5." },
      { side: "b", from: "f8", to: "e7", explanation: "Breaking the pin and preparing to castle. Black keeps the position solid." },
      { side: "w", from: "e2", to: "e3", explanation: "White supports d4 and opens the diagonal for the light-squared bishop." },
      { side: "b", from: "e8", to: "g8", explanation: "Castling kingside — the king is safe and Black is ready for the middlegame." },
    ],
  },
  {
    key: "slav_defense",
    name: "Slav Defense",
    description: "Support the center with c6 instead of e6, keeping the light-squared bishop free.",
    playerColor: "b",
    moves: [
      { side: "w", from: "d2", to: "d4", explanation: "White opens with d4." },
      { side: "b", from: "d7", to: "d5", explanation: "Black establishes a central pawn." },
      { side: "w", from: "c2", to: "c4", explanation: "The Queen's Gambit." },
      { side: "b", from: "c7", to: "c6", explanation: "The Slav Defense — Black supports d5 with c6 instead of e6, keeping the light-squared bishop unblocked. This is the key difference from the QGD." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight and prepares the center." },
      { side: "b", from: "g8", to: "f6", explanation: "Black develops and pressures e4." },
      { side: "w", from: "b1", to: "c3", explanation: "White reinforces the center." },
      { side: "b", from: "d5", to: "c4", explanation: "The Slav Accepted — Black captures the c4 pawn, gaining a free piece of the gambit." },
      { side: "w", from: "a2", to: "a4", explanation: "Preventing b5, which would let Black hold the extra pawn." },
      { side: "b", from: "c8", to: "f5", explanation: "The critical move — Black develops the bishop outside the pawn chain before playing e6, a key advantage of the Slav over the QGD." },
    ],
  },
  {
    key: "kings_indian_defense",
    name: "King's Indian Defense",
    description: "A dynamic, fighting defense — let White build the center, then attack it with pieces.",
    playerColor: "b",
    moves: [
      { side: "w", from: "d2", to: "d4", explanation: "White opens with d4." },
      { side: "b", from: "g8", to: "f6", explanation: "The King's Indian starts here — Black develops the knight to its ideal square immediately." },
      { side: "w", from: "c2", to: "c4", explanation: "White expands, aiming for a large center." },
      { side: "b", from: "g7", to: "g6", explanation: "Preparing to fianchetto the bishop — the defining move of the King's Indian." },
      { side: "w", from: "b1", to: "c3", explanation: "White develops and controls d5." },
      { side: "b", from: "f8", to: "g7", explanation: "The fianchettoed bishop on g7 is Black's most powerful piece, targeting White's entire center." },
      { side: "w", from: "e2", to: "e4", explanation: "White completes the ideal pawn center with both d4 and e4." },
      { side: "b", from: "d7", to: "d6", explanation: "Preparing e5, which is the thematic King's Indian counter-thrust." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops and prepares to castle." },
      { side: "b", from: "e8", to: "g8", explanation: "Castling into safety. Black is set up to launch a fierce kingside attack with e5 or c5." },
    ],
  },
  {
    key: "nimzo_indian_defense",
    name: "Nimzo-Indian Defense",
    description: "Pin White's knight with the bishop and create long-term positional pressure.",
    playerColor: "b",
    moves: [
      { side: "w", from: "d2", to: "d4", explanation: "White opens with d4." },
      { side: "b", from: "g8", to: "f6", explanation: "Developing the knight, controlling the center." },
      { side: "w", from: "c2", to: "c4", explanation: "White plays the Queen's Gambit setup." },
      { side: "b", from: "e7", to: "e6", explanation: "Black prepares the Nimzo-Indian — e6 keeps the center flexible." },
      { side: "w", from: "b1", to: "c3", explanation: "White develops the knight — exactly the move Black was waiting for." },
      { side: "b", from: "f8", to: "b4", explanation: "The Nimzo-Indian! Black pins the knight, preventing e4 and creating the threat of doubling White's c-pawns by taking on c3." },
      { side: "w", from: "e2", to: "e3", explanation: "White reinforces the center and supports d4, accepting a slightly passive but solid setup." },
      { side: "b", from: "e8", to: "g8", explanation: "Castling to safety while the position is still calm." },
      { side: "w", from: "g1", to: "f3", explanation: "White develops the knight." },
      { side: "b", from: "d7", to: "d5", explanation: "Striking at the center — Black challenges White's control of d4 and opens lines for the pieces." },
    ],
  },

  // ── White openings (player as White) ─────────────────────────────────────

  {
    key: "london_system",
    name: "London System",
    description: "A solid, low-theory White system built around d4, Nf3, and Bf4.",
    playerColor: "w",
    moves: [
      { side: "w", from: "d2", to: "d4", explanation: "White opens with d4, controlling the center." },
      { side: "b", from: "d7", to: "d5", explanation: "Black mirrors with d5, claiming equal center space." },
      { side: "w", from: "g1", to: "f3", explanation: "Developing the knight toward the center." },
      { side: "b", from: "g8", to: "f6", explanation: "Black develops symmetrically." },
      { side: "w", from: "c1", to: "f4", explanation: "The London System's key move — the bishop develops to f4 before the pawn structure closes it in." },
      { side: "b", from: "e7", to: "e6", explanation: "Black solidifies the center and prepares to develop the kingside." },
      { side: "w", from: "e2", to: "e3", explanation: "Supporting d4 and opening the diagonal for the f1 bishop. A compact, solid structure." },
      { side: "b", from: "c7", to: "c5", explanation: "Black challenges the center with c5, the most active response." },
      { side: "w", from: "c2", to: "c3", explanation: "Reinforcing d4 and maintaining the solid London pawn triangle. White declines to open the center prematurely." },
      { side: "b", from: "b8", to: "c6", explanation: "Black develops the queenside knight, building toward a middlegame battle." },
    ],
  },
  {
    key: "english_opening",
    name: "English Opening",
    description: "A hypermodern flank opening — control the center with pieces rather than pawns.",
    playerColor: "w",
    moves: [
      { side: "w", from: "c2", to: "c4", explanation: "The English Opening — controlling d5 from the flank rather than occupying the center directly." },
      { side: "b", from: "e7", to: "e5", explanation: "Black stakes the center immediately, claiming space." },
      { side: "w", from: "b1", to: "c3", explanation: "White develops and supports d5 while putting pressure on e5." },
      { side: "b", from: "g8", to: "f6", explanation: "Black develops the knight, supporting e5 and eying d5." },
      { side: "w", from: "g2", to: "g3", explanation: "Preparing to fianchetto the bishop — a flexible, hypermodern approach to controlling the center." },
      { side: "b", from: "d7", to: "d5", explanation: "Black strikes in the center, trying to limit the c4 bishop before it arrives." },
      { side: "w", from: "c4", to: "d5", explanation: "White captures, opening the position and activating pieces." },
      { side: "b", from: "f6", to: "d5", explanation: "Black recaptures with the knight, maintaining piece activity." },
      { side: "w", from: "f1", to: "g2", explanation: "The fianchettoed bishop arrives — it now dominates the long diagonal and pressures Black's position." },
      { side: "b", from: "d5", to: "b6", explanation: "Black retreats the knight to safety as White prepares to castle and complete development." },
    ],
  },
];

export default OPENINGS;
